workflows:
  internet-powerful-v45:
    name: Internet Powerful V45
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      java: 17

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Obtener SHA-1
        script: |
          ./gradlew signingReport

      - name: Build Internet Powerful V45 APK
        script: |
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk
